image: docker:latest

stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.8-alpine
  script:
    - pip install flake8
    - flake8 --statistics

test:
  stage: test
  image: python:3.8
  before_script:
  script:
    - pip install virtualenv
    - ./scripts/install_test.sh
    - ./scripts/run_tests.sh
