name: "Back CI"

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    stage: lint
    image: python:3.8-alpine
    script:
      - pip install flake8
      - flake8 --statistics

  test:
    runs-on: ubuntu-latest
    stage: test
    image: python:3.8
    before_script:
    script:
      - pip install virtualenv
      - ./scripts/install_test.sh
      - ./scripts/run_tests.sh
