name: Build latex document

on: push

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install tools
        run: ./.github/workflows/latex.sh
      - name: Generate pdf
        run: ./generate_pdf.sh