name: Build latex document

on:
  push:
    tags:
      - '*'

jobs:
  generate-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: .github/workflows/latex-install.sh
      - name: Generate pdf
        run: ./generate_pdf.sh