name: Build latex document

on: push

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: ./latex-install.sh
      - name: Generate pdf
        run: ./generate_pdf.sh