name: Python CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Instala poetry
        run: pip install poetry
      - name: move to folder
        run: cd code/
      - name: Instala las dependencias
        run: |
          cd code/
          poetry install
          poetry run lint
          poetry run test
