name: Python CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Instala poetry
        run: |
          pip install poetry
          poetry install
      - name: move to folder
        run: cd code/
      - name: Instala las dependencias
        run: poetry install
      - name: Run lint task
        run: poetry run task lint
      - name: Run test task
        run: poetry run task test
